Feature: Header-2 hizli link erisilebilirlik kontrolu
  Header-2 alanindaki ana linklerin calisip calismadigini hizli sekilde kontrol etmek istiyorum.

  Scenario Outline: Header-2 linkleri hizli kontrolde erisilebilir olmali
    Given I run a quick link availability check on "<url>"
    Then the quick link check should be successful

    Examples:
      | pageName              | url                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | Header-2-Aday-Ogrenci | https://adayogrenciler.nny.edu.tr/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | Header-2-Web-Mail     | https://www.nny.edu.tr/?p=content&id=65                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | Header-2-OBIS         | https://giris.turkiye.gov.tr/Giris/gir?oauthClientId=93b5a8e9-1294-4fe2-8b25-7ebaaab4f183&continue=https%3A%2F%2Fgiris.turkiye.gov.tr%2FOAuth2AuthorizationServer%2FAuthorizationController%3Fresponse_type%3Dcode%26client_id%3D93b5a8e9-1294-4fe2-8b25-7ebaaab4f183%26state%3DOgrenci%257CJohfLdHuUCehXpKs86dOQF8C389YxaRk7gOgwTAkxscm0VLNineFHP7Ao9uVyEM8wKuCxFgh7F2xvoclE3IQLVtIs3pq%25252fQlsCZNF2YLl%25252bqtGKwSHYpqCiCEp9JUAFB1cdtzpcotNkHtbOryHRmff7pwEF7Pm2DzXRAZOveS3ohCKji5nyHQong%25253d%25253d%257C0%26scope%3DKimlik-Dogrula%253BAd-Soyad%26redirect_uri%3Dhttps%253A%252F%252Fobs.nny.edu.tr%252Frouter.aspx%26code_challenge_method%3DS256%26code_challenge%3DqQvPTdR_xYi3pf18-B9fRf6ORLk9OsZ5SRuLOql912w                          |
      | Header-2-ABIS         | https://giris.turkiye.gov.tr/Giris/gir?oauthClientId=93b5a8e9-1294-4fe2-8b25-7ebaaab4f183&continue=https%3A%2F%2Fgiris.turkiye.gov.tr%2FOAuth2AuthorizationServer%2FAuthorizationController%3Fresponse_type%3Dcode%26client_id%3D93b5a8e9-1294-4fe2-8b25-7ebaaab4f183%26state%3DAkademik%257ClRFVPanjr5mRYJzz1F45pCAMawHacP5y4OcwnQXor%25252fJmTj4JVuhxDK4pUqc2zv7kuoNieqi3ugCBw3094IEPK%25252fbN0ArCouK%25252fywoM0SNdE9rdiOjHfHSwsYeVLy%25252fySLSkBT2xqnjlayE5badxOnRdCkz2%25252bjNFoEpX3MjAhx%25252frpgyKji5nyHQong%25253d%25253d%257C0%26scope%3DKimlik-Dogrula%253BAd-Soyad%26redirect_uri%3Dhttps%253A%252F%252Fobs.nny.edu.tr%252Frouter.aspx%26code_challenge_method%3DS256%26code_challenge%3DPxXFZxCUwnf3D8pESX1NdO28XFTwLp0lgnrYfz-E3QE |
      | Header-2-EBYS         | https://ebys.nny.edu.tr/index.html                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | Header-2-Kutuphane    | https://kutuphane.nny.edu.tr/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | Header-2-Kurumsal     | https://www.nny.edu.tr/index.php?p=content&id=68                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | Header-2-Rehber       | https://www.nny.edu.tr/index.php?p=content&id=69                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | Header-2-Iletisim     | https://bpmyo.nny.edu.tr/?p=contact                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
